version: '3.8'

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    networks:
      - shared-network
    environment:
      - REACT_APP_SERVER_BASEURL=http://backend:8081
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - 8081:8081
    environment:
      - PORT = 8081
    env_file:
      - ./.env
    networks:
      - shared-network

networks:
  shared-network:
