version: '3.8'

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_BASEURL=http://backend:8081
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - 8081:8081
